### ISSUE TITLE
add global configuration "files"

### ISSUE THREAD

**Issue by DavidBadura** [simpspector/analyser#53]
so you don't always have to specify the path

before:

``` yaml
phpmd:
  files: src/
pdepend:
  files: src/
```

after:

``` yaml
global:
  files: src/
phpmd: ~
pdepend: ~
```
